### ISSUE TITLE
I met an error while training my own dataset: IndexError: index 0 is out of bounds for dimension 0 with size 0

### ISSUE THREAD

**Issue by miyajiyuta** [NVlabs/DiscoBox#14]
Thanks for your nice implementation.
I have tried DiscoBox to train my own dataset and met the following error.
I used [this config file](https://github.com/NVlabs/DiscoBox/blob/main/configs/discobox/discobox_solov2_r50_fpn_3x.py), with changing dataset path and classes info.

```sh
Traceback (most recent call last):
  File "tools/train.py", line 191, in <module>
    main()
  File "tools/train.py", line 180, in main
    train_detector(
  File "/workspace/mmdet/apis/train.py", line 172, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/opt/conda/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/workspace/mmdet/models/detectors/base.py", line 251, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/workspace/mmdet/models/detectors/base.py", line 185, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/workspace/mmdet/models/detectors/single_stage_wsis.py", line 206, in forward_train
    losses = self.bbox_head.loss(
  File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 140, in decorate_autocast
    return func(*args, **kwargs)
  File "/workspace/mmdet/models/dense_heads/discobox_solov2_head.py", line 1329, in loss
    ins_label_list, cate_label_list, ins_ind_label_list, grid_order_list = multi_apply(
  File "/workspace/mmdet/core/utils/misc.py", line 29, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/workspace/mmdet/models/dense_heads/discobox_solov2_head.py", line 1620, in solov2_target_single
    device = gt_labels_raw[0].device
IndexError: index 0 is out of bounds for dimension 0 with size 0
```

This error seems `gt_labels_raw` is empty. But images in my dataset have at least one bbox.
Could you suggest some clues to solve this problem?
Thanks.

**Comment by voidrank** [comment]
Hi @miyajiyuta ,

Please doubly check whether "images in my dataset have at least one bbox" and whether those boxes are not filtered in the data provider.

Best,

Shiyi

**Comment by miyajiyuta** [comment]
@voidrank 
Thank you for your reply!

Sorry. I used wrong dataset, which has invalid bbox annotations (e.g., bbox outside of an image).
I succeeded in training after removing the invalid data.
I am sorry to have caused trouble.
Thanks.
