### ISSUE TITLE
KeyError: 'DiscoBoxSOLOv2 is not in the models registry' running visualization

### ISSUE THREAD

**Issue by robonrrd** [NVlabs/DiscoBox#6]
I am able to run the COCO (ResNeXt-101-DCN) test successfully, but when I try to run your visualization example:
```
python tools/test.py configs/discobox/discobox_solov2_x101_dcn_fpn_3x.py coco_x101_dcn_fpn_3x.pth --show --show-dir discobox_vis_x101
```
I get the following errors:
```
root@mymachine:~/src/github/DiscoBox# python tools/test.py configs/discobox/discobox_solov2_x101_dcn_fpn_3x.py coco_x101_dcn_fpn_3x.pth --show --show-dir discobox_vis_x101
/root/src/github/mmdetection/mmdet/datasets/api_wrappers/coco_api.py:20: UserWarning: mmpycocotools is deprecated. Please install official pycocotools by "pip install pycocotools"
  warnings.warn(
loading annotations into memory...
Done (t=0.51s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/test.py", line 222, in <module>
    main()
  File "tools/test.py", line 175, in main
    model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/root/src/github/mmdetection/mmdet/models/builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'DiscoBoxSOLOv2 is not in the models registry'
```
How do I add the DiscoBox models to mmcv's registry? 

My build info:
I am using your Docker container (on Ubuntu 20.04 with CUDA 11.4), with mmcv-full version 1.3.17 and latest (as of July 15, 2022) master of mmdetection.

**Comment by voidrank** [comment]
Hi @robonrrd 

It seems like you install the official mmdetection instead of DiscoBox. I suggest that you follow the instruction to install DiscoBox.

**Comment by robonrrd** [comment]
I followed your instructions here: https://github.com/NVlabs/DiscoBox/blob/main/docs/get_started.md
```
4. Clone the MMDetection repository.
   git clone https://github.com/open-mmlab/mmdetection.git
   cd mmdetection

5. Install build requirements and then install MMDetection. 
   pip install -r requirements/build.txt
   pip install -v -e .  # or "python setup.py develop"
```

**Comment by voidrank** [comment]
Can you try this ?

4. Clone the MMDetection repository.

    ```shell
    git clone git clone https://github.com/NVlabs/DiscoBox.git
    cd DiscoBox
    ```

5. Install build requirements and then install MMDetection.

    ```shell
    pip install -r requirements/build.txt
    pip install -v -e .  # or "python setup.py develop"
    ```

**Comment by voidrank** [comment]
Let me know if you fix it, thanks!

**Comment by robonrrd** [comment]
`pip install -r requirements/build.txt` did nothing (cython and numpy are already installed in the Docker container) but `pip install -v -e .` in the DiscoBox top directory seemed to fix my issue.  Thank you for the help!
